Repository NREL/floris, pull requests merged in 2022-11, with the labels that each got.

#514 Move docs to Jupyter Book and expand content
  .github/workflows/deploy-pages.yaml
  .gitignore
  README.md
  docs/.nojekyll
  docs/_config.yml
  docs/_devdocs/codecoverage.html
  docs/_devdocs/plot_metrics.py
  docs/_devdocs/quality.md
  docs/_devdocs/timing.html
  docs/_templates/custom-class-template.rst
  docs/_templates/custom-module-template.rst
  docs/_toc.yml
  docs/_tutorials/index.md
  docs/api_docs.rst
  docs/assets/images/00_getting_started/00_getting_started_18_1.png
  docs/assets/images/00_getting_started/00_getting_started_20_1.png
  docs/assets/images/00_getting_started/00_getting_started_20_2.png
  docs/assets/images/00_getting_started/00_getting_started_23_2.png
  docs/assets/images/00_getting_started/00_getting_started_34_1.png
  docs/assets/images/00_getting_started/00_getting_started_39_1.png
  docs/assets/images/00_getting_started/00_getting_started_8_2.png
  docs/background_concepts.ipynb
  docs/cc.yaml
  docs/code_quality.ipynb
  docs/dev_guide.md
  docs/examples.md
  docs/gch.gif
  docs/gch.yaml
  docs/index.md
  docs/input_reference.rst
  docs/installation.md
  docs/intro.md
  docs/jensen.yaml
  docs/notebook2md.py
  docs/references.bib
  docs/requirements.txt
  examples/00_getting_started.ipynb
  examples/inputs/gch.yaml
Labels: enhancement, v3

#519 Update documentation references list
  docs/references.bib
  floris/simulation/wake_combination/max.py
  floris/simulation/wake_deflection/gauss.py
  floris/simulation/wake_deflection/jimenez.py
  floris/simulation/wake_turbulence/crespo_hernandez.py
  floris/simulation/wake_velocity/cumulative_gauss_curl.py
  floris/simulation/wake_velocity/jensen.py
  floris/tools/wind_rose.py
Labels: enhancement

#532 Remove requirement to use codecov token to upload reports
  .github/workflows/continuous-integration-workflow.yaml
Labels: bug

#512 FLORIS Tools API improvements
  examples/01_opening_floris_computing_power.py
  examples/02_visualizations.py
  examples/03_making_adjustments.py
  examples/04_sweep_wind_directions.py
  examples/05_sweep_wind_speeds.py
  examples/06_sweep_wind_conditions.py
  examples/08_calc_aep_from_rose_use_class.py
  examples/09_compare_farm_power_with_neighbor.py
  examples/17_multiple_turbine_types.py
  examples/18_check_turbine.py
  examples/19_streamlit_demo.py
  examples/22_get_wind_speed_at_turbines.py
  floris/tools/cut_plane.py
  floris/tools/floris_interface.py
  floris/tools/visualization.py
  floris/tools/wind_rose.py
  tests/floris_interface_test.py
Labels: enhancement, v3, floris.tools
