Repository NREL/floris, pull requests merged in 2022-04, with the labels that each got.

#408 Add GH Action to ensure examples run
  .github/workflows/check-working-examples.yaml
  docs/_tutorials/index.md
  docs/assets/images/00_getting_started/00_getting_started_34_1.png
  examples/00_getting_started.ipynb
Labels: enhancement, v3

#407 Bugfix: Resolve issues with no_wake=True
  floris/simulation/floris.py
  floris/tools/floris_interface.py
  floris/tools/uncertainty_interface.py
Labels: bug, v3

#410 Create all Grid data at initialization
  docs/_tutorials/index.md
  docs/assets/images/00_getting_started/00_getting_started_34_1.png
  examples/00_getting_started.ipynb
  floris/simulation/floris.py
  floris/simulation/grid.py
Labels: v3

#424 Bugfix: using the wrong rotor diameters when plotting with the CC model
  examples/02_visualizations.py
  floris/simulation/solver.py
Labels: bug, v3
