Repository NREL/floris, pull requests merged in 2022-03, with the labels that each got.

#358 Feature: add IEA 15MW turbine
  examples/15_check_turbine.py
  floris/turbine_library/iea_15MW.yaml
  floris/turbine_library/nrel_5MW.yaml
  tests/conftest.py
Labels: enhancement, v3

#367 Correcting bound for boundary constraint; removing hard-coded rotor diameter
  floris/tools/optimization/pyoptsparse/layout.py
Labels: bug, v3

#368 Rename version file to Python
  floris/__init__.py
  floris/version.py
  setup.py
Labels: bug, v3

#370 Include yaw_optimization in package init
  floris/tools/optimization/__init__.py
Labels: bug, v3

#374 Add missing __init__.py to yaw optimization module
  floris/tools/optimization/yaw_optimization/__init__.py
Labels: bug, v3

#384 Selectively invert plot axis via normal vector in CutPlane
  floris/tools/cut_plane.py
  floris/tools/floris_interface.py
  floris/tools/visualization.py
Labels: enhancement, v3

#369 Redesign AEP calculation function
  examples/07_calc_aep_from_rose.py
  floris/tools/floris_interface.py
Labels: bug, enhancement, v3

#382 Add cut out and default reference option
  examples/15_check_turbine.py
  examples/inputs/cc.yaml
  examples/inputs/gch.yaml
  examples/inputs/gch_multiple_turbine_types.yaml
  examples/inputs/jensen.yaml
  floris/simulation/flow_field.py
  floris/simulation/turbine.py
  floris/tools/floris_interface.py
  floris/turbine_library/iea_10MW.yaml
  floris/turbine_library/iea_15MW.yaml
  floris/turbine_library/nrel_5MW.yaml
Labels: bug, enhancement, v3

#388 Save yaw angles for reset in plane visualizations
  floris/tools/floris_interface.py
Labels: bug, v3

#386 Documentation improvements
  README.md
  docs/_devdocs/index.md
  docs/_tutorials/index.md
  docs/assets/images/00_getting_started/00_getting_started_18_1.png
  docs/assets/images/00_getting_started/00_getting_started_20_1.png
  docs/assets/images/00_getting_started/00_getting_started_20_2.png
  docs/assets/images/00_getting_started/00_getting_started_23_2.png
  docs/assets/images/00_getting_started/00_getting_started_39_1.png
  docs/assets/images/00_getting_started/00_getting_started_8_2.png
  docs/index.md
  docs/notebook2md.py
  examples/00_getting_started.html
  examples/00_getting_started.ipynb
Labels: v3

#393 Remove energy ratio tools in favor of FLASC
  floris/tools/__init__.py
  floris/tools/energy_ratio.py
  floris/tools/energy_ratio_single.py
  floris/tools/energy_wake_loss.py
Labels: v3

#308 Feature/include unc
  examples/17_calculate_farm_power_with_uncertainty.py
  floris/tools/__init__.py
  floris/tools/floris_interface.py
  floris/tools/optimization/yaw_optimization/yaw_optimization_base.py
  floris/tools/uncertainty_interface.py
Labels: enhancement, v3

#404 Improve CLI in LegacyInterface
  floris/tools/floris_interface_legacy_reader.py
Labels: enhancement, v3
