Repository NREL/floris, pull requests merged in 2022-07, with the labels that each got.

#456 pass in het map when copying fi
  floris/tools/floris_interface.py
Labels: bug

#470 Bug fix: Convert `layout` to `layout_x` and `layout_y` in `FlorisInterface.reinitalize`
  .pre-commit-config.yaml
  examples/00_getting_started.ipynb
  examples/01_opening_floris_computing_power.py
  examples/03_making_adjustments.py
  examples/04_sweep_wind_directions.py
  examples/05_sweep_wind_speeds.py
  examples/06_sweep_wind_conditions.py
  examples/07_calc_aep_from_rose.py
  examples/08_opt_yaw_single_ws.py
  examples/09_opt_yaw_multiple_ws.py
  examples/10_optimize_yaw.py
  examples/11_optimize_layout.py
  examples/12_compare_yaw_optimizers.py
  examples/15_check_turbine.py
  examples/16_streamlit_demo.py
  examples/17_calculate_farm_power_with_uncertainty.py
  examples/18_demo_time_series.py
  examples/18_get_wind_speed_at_turbines.py
  floris/tools/floris_interface.py
  floris/tools/optimization/pyoptsparse/layout.py
  floris/tools/uncertainty_interface.py
Labels: bug, floris.tools

#432 Issue alert if calc wake needs to be run
  floris/simulation/__init__.py
  floris/simulation/base.py
  floris/simulation/farm.py
  floris/simulation/floris.py
  floris/tools/floris_interface.py
Labels: enhancement

#439 Add wake deflection to the TurbOPark wake deficit model
  floris/simulation/solver.py
  floris/simulation/wake_velocity/turbopark.py
  floris/tools/floris_interface.py
  tests/reg_tests/cumulative_curl_regression_test.py
  tests/reg_tests/turbopark_regression_test.py
Labels: enhancement
