Repository NREL/floris, pull requests merged in 2023-11, with the labels that each got.

#727 Add documentation for the release process
  docs/dev_guide.md
Labels: enhancement, documentation

#736 Catch documentation and examples errors
  .github/workflows/check-working-examples.yaml
  .github/workflows/continuous-integration-workflow.yaml
  docs/_config.yml
  docs/_toc.yml
  docs/index.md
  docs/reference.md
  docs/references.bib
  floris/simulation/floris.py
  floris/simulation/flow_field.py
  floris/simulation/turbine.py
  floris/simulation/turbine_multi_dim.py
  floris/simulation/wake_combination/fls.py
  floris/simulation/wake_combination/max.py
  floris/simulation/wake_combination/sosfs.py
  floris/simulation/wake_deflection/empirical_gauss.py
  floris/simulation/wake_deflection/jimenez.py
  floris/simulation/wake_velocity/cumulative_gauss_curl.py
  floris/simulation/wake_velocity/empirical_gauss.py
  floris/simulation/wake_velocity/gauss.py
  floris/simulation/wake_velocity/turbopark.py
  floris/tools/__init__.py
  floris/tools/cc_blade_utilities.py
  floris/tools/cut_plane.py
  floris/tools/floris_interface.py
  floris/tools/flow_data.py
  floris/tools/optimization/legacy/pyoptsparse/optimization.py
  floris/tools/optimization/legacy/pyoptsparse/yaw.py
  floris/tools/optimization/legacy/scipy/optimization.py
  floris/tools/optimization/legacy/scipy/yaw_clustered.py
  floris/tools/optimization/legacy/scipy/yaw_wind_rose_clustered.py
  floris/tools/optimization/legacy/scipy/yaw_wind_rose_parallel.py
  floris/tools/optimization/legacy/scipy/yaw_wind_rose_parallel_clustered.py
  floris/tools/sowfa_utilities.py
  floris/type_dec.py
  setup.py
Labels: bug, enhancement, documentation

#721 Fix errors in notebooks for online documentation
  docs/floris_101.ipynb
Labels: bug, documentation

#739 Support relative paths in YAML configuration files
  .github/workflows/check-working-examples.yaml
  examples/18_check_turbine.py
  floris/simulation/farm.py
  floris/simulation/turbine_multi_dim.py
  floris/tools/floris_interface.py
  floris/turbine_library/iea_15MW_floating_multi_dim_cp_ct.yaml
  floris/type_dec.py
Labels: bug, enhancement, floris.tools, documentation, floris.simulation

#748 Use compatible-release specifier for dependency versions
  setup.py
Labels: enhancement
