Repository NREL/floris, pull requests merged in 2023-04, with the labels that each got.

#632 Use setup.py for all installs
  .github/workflows/check-working-examples.yaml
  .github/workflows/deploy-pages.yaml
  docs/dev_guide.md
  docs/requirements.txt
  requirements.txt
  setup.py
Labels: documentation

#636 Pin Jupyter Book version
  docs/dev_guide.md
  setup.py
Labels: bug, documentation

#637 Bug fix: Fix error message in `FromDictMixin`
  floris/type_dec.py
Labels: bug

#630 Add documentation for high level FLORIS architecture
  docs/_config.yml
  docs/_toc.yml
  docs/architecture.md
  floris/type_dec.py
  setup.py
Labels: documentation
