Repository NREL/floris, pull requests merged in 2023-05, with the labels that each got.

#645 Docs: Update timing tests with results from Eagle
  docs/code_quality.ipynb
Labels: enhancement, documentation

#646 Improve error handling and robustness in turbine model loads
  .pre-commit-config.yaml
  floris/simulation/farm.py
  floris/simulation/floris.py
  floris/tools/floris_interface.py
  floris/tools/uncertainty_interface.py
  floris/type_dec.py
  floris/utilities.py
  profiling/profiling.py
  tests/conftest.py
  tests/data/input_full_v3.json
  tests/farm_unit_test.py
  tests/floris_interface_test.py
  tests/floris_unit_test.py
  tests/type_dec_unit_test.py
Labels: bug, enhancement

#631 Documentation: Add a wake model description page
  .gitignore
  docs/_config.yml
  docs/_toc.yml
  docs/bibliography.md
  docs/wake_models.ipynb
Labels: documentation

#647 Print error when turbine models are missing reference values
  docs/_toc.yml
  docs/input_reference.md
  docs/input_reference_main.md
  docs/input_reference_turbine.md
  docs/nrel_5MW.yaml
  floris/simulation/floris.py
  floris/turbine_library/nrel_5MW.yaml
  tests/data/nrel_5MW.yaml
  tests/data/nrel_5MW_custom.yaml
Labels: enhancement

#648 Add CI branch for Python 3.8 and 3.10, update Ruff
  .github/workflows/check-working-examples.yaml
  .github/workflows/continuous-integration-workflow.yaml
  .github/workflows/deploy-pages.yaml
  .github/workflows/quality-metrics-workflow.yaml
  examples/16_heterogeneous_inflow.py
  floris/tools/optimization/legacy/scipy/cluster_turbines.py
  floris/tools/optimization/legacy/scipy/derive_downstream_turbines.py
  floris/tools/optimization/yaw_optimization/yaw_optimization_tools.py
Labels: enhancement

#650 Add support for probing velocities at arbitrary flow field points
  docs/examples.md
  examples/25_extract_wind_speed_at_points.py
  floris/simulation/__init__.py
  floris/simulation/floris.py
  floris/simulation/grid.py
  floris/simulation/solver.py
  floris/tools/floris_interface.py
  floris/tools/visualization.py
  floris/utilities.py
  tests/conftest.py
  tests/utilities_unit_test.py
Labels: enhancement

#651 Disable user-provided tilt angle settings in wake calculation
  floris/simulation/farm.py
  floris/tools/floris_interface.py
Labels: enhancement

#649 Add cubature integration method for rotor velocities
  floris/simulation/__init__.py
  floris/simulation/farm.py
  floris/simulation/floris.py
  floris/simulation/grid.py
  floris/simulation/solver.py
  floris/simulation/turbine.py
  floris/tools/floris_interface.py
  floris/type_dec.py
  tests/data/input_full_v3.yaml
  tests/reg_tests/none_regression_test.py
  tests/turbine_unit_test.py
Labels: enhancement

#578 Add coordinates from inertial frame to grid class
  examples/02_visualizations.py
  examples/03_making_adjustments.py
  examples/16_heterogeneous_inflow.py
  examples/16b_heterogenaity_multiple_ws_wd.py
  examples/inputs/gch_heterogeneous_inflow.yaml
  floris/simulation/flow_field.py
  floris/simulation/grid.py
  floris/tools/floris_interface.py
  floris/tools/parallel_computing_interface.py
  floris/tools/uncertainty_interface.py
  floris/tools/visualization.py
  floris/utilities.py
Labels: enhancement
