Repository NREL/floris, pull requests merged in 2023-07, with the labels that each got.

#665 Bug fix: Finalize Farm attributes
  floris/simulation/farm.py
Labels: bug

#494 Performance Improvements and Code Simplification
  floris/simulation/solver.py
  floris/simulation/turbine.py
  floris/simulation/wake_deflection/empirical_gauss.py
  floris/simulation/wake_deflection/gauss.py
  floris/simulation/wake_turbulence/crespo_hernandez.py
  floris/simulation/wake_velocity/cumulative_gauss_curl.py
  floris/simulation/wake_velocity/empirical_gauss.py
  floris/simulation/wake_velocity/gauss.py
  floris/simulation/wake_velocity/jensen.py
  floris/simulation/wake_velocity/turbopark.py
  pyproject.toml
Labels: enhancement

#677 Infrastructure updates
  docs/architecture.md
  docs/code_quality.ipynb
  floris/simulation/floris.py
  floris/simulation/grid.py
  floris/simulation/wake_deflection/gauss.py
  floris/tools/floris_interface.py
Labels: enhancement, documentation

#679 Bug fix: Add variable wind shear to GCH calculations
  floris/simulation/solver.py
  floris/simulation/wake_deflection/gauss.py
Labels: bug

#678 Enable heterogeneous inflows in yaw optimization routines
  floris/simulation/turbine.py
  floris/tools/floris_interface.py
  floris/tools/optimization/yaw_optimization/yaw_optimization_base.py
  floris/tools/optimization/yaw_optimization/yaw_optimizer_scipy.py
  floris/tools/optimization/yaw_optimization/yaw_optimizer_sr.py
Labels: bug, enhancement
