Repository NREL/floris, pull requests merged in 2024-06, with the labels that each got.

#915 Add z/3d to HeterogeneousMap
  docs/heterogeneous_map.ipynb
  examples/examples_heterogeneous/002_heterogeneous_using_wind_data.py
  examples/examples_heterogeneous/004_heterogeneous_2d_and_3d.py
  floris/floris_model.py
  floris/heterogeneous_map.py
  tests/heterogeneous_map_integration_test.py
Labels: enhancement

#930 [BUGFIX] Fix wind rose plots
  floris/wind_data.py
Labels: bug

#932 Add link to GRS layout optimization paper
  docs/heterogeneous_map.ipynb
  docs/layout_optimization.md
  docs/references.bib
  floris/optimization/layout_optimization/layout_optimization_random_search.py
Labels: documentation
