Repository NREL/floris, pull requests merged in 2024-04, with the labels that each got.

#859 Change `power_thrust_model` key to `operation_model` at the user level
  examples/40_test_derating.py
  examples/41_test_disable_turbines.py
  floris/core/turbine/turbine.py
  floris/floris_model.py
  floris/turbine_library/iea_10MW.yaml
  floris/turbine_library/iea_15MW.yaml
  floris/turbine_library/nrel_5MW.yaml
  floris/turbine_library/turbine_utilities.py
  tests/conftest.py
  tests/floris_model_integration_test.py
Labels: bug, v4

#856 [BUGFIX] hardcoded reset to first turbine type in set_operation_model
  floris/floris_model.py
  tests/floris_model_integration_test.py
Labels: bug, v4

#862 Enabling layout optimization for value
  floris/floris_model.py
  floris/optimization/layout_optimization/layout_optimization_base.py
  floris/optimization/layout_optimization/layout_optimization_pyoptsparse.py
  floris/optimization/layout_optimization/layout_optimization_scipy.py
  floris/wind_data.py
  tests/floris_model_integration_test.py
  tests/reg_tests/scipy_layout_opt_regression.py
  tests/reg_tests/scipy_layout_opt_regression_test.py
Labels: enhancement, v4

#867 [BUGFIX] set_operation_model ordering with layout
  floris/core/farm.py
  floris/floris_model.py
  tests/floris_model_integration_test.py
Labels: bug, v4

#869 Make set_operation method public
  floris/floris_model.py
  floris/optimization/layout_optimization/layout_optimization_scipy.py
  tests/floris_model_integration_test.py
Labels: enhancement, v4

#872 Fixing datatype of value in WindData objects
  floris/floris_model.py
  floris/wind_data.py
Labels: bug, v4

#860 Build out v4 documentation
  .github/workflows/check-working-examples.yaml
  .github/workflows/deploy-pages.yaml
  .gitignore
  README.md
  docs/_config.yml
  docs/_toc.yml
  docs/architecture.md
  docs/empirical_gauss_model.md
  docs/examples.md
  docs/floating_wind_turbine.md
  docs/index.md
  docs/installation.md
  docs/operation_models_user.ipynb
  docs/powerthrust_helix.png
  docs/turbine_interaction.ipynb
  docs/v3_to_v4.md
  docs/wind_data_user.ipynb
  examples/_convert_examples_to_notebooks.py
  examples/examples_layout_optimization/001_optimize_layout.py
  examples/examples_layout_optimization/002_optimize_layout_with_heterogeneity.py
  examples/examples_uncertain/002_yaw_inertial_frame.py
  examples/inputs/gch.yaml
  floris/turbine_library/nrel_5MW.yaml
  floris/turbine_library/turbine_previewer.py
  floris/version.py
Labels: documentation, v4

#866 Add merge/reduce FLORIS objects
  floris/floris_model.py
Labels: v4

#868 Remove setpoints and wind condition specifics from calculate_XX_plane methods
  examples/examples_control_types/004_helix_active_wake_mixing.py
  examples/examples_emgauss/001_empirical_gauss_velocity_deficit_parameters.py
  examples/examples_emgauss/002_empirical_gauss_deflection_parameters.py
  examples/examples_visualizations/001_layout_visualizations.py
  floris/floris_model.py
  floris/flow_visualization.py
  tests/floris_model_integration_test.py
Labels: enhancement, v4

#875 Update Empirical Gaussian default deflection_rate
  examples/inputs/emgauss.yaml
  examples/inputs/gch_multi_dim_cp_ct.yaml
  examples/inputs_floating/emgauss_fixed.yaml
  examples/inputs_floating/emgauss_floating.yaml
  examples/inputs_floating/emgauss_floating_fixedtilt15.yaml
  examples/inputs_floating/emgauss_floating_fixedtilt5.yaml
  floris/core/wake_deflection/empirical_gauss.py
  tests/conftest.py
  tests/reg_tests/empirical_gauss_regression_test.py
Labels: enhancement, v4

#857 Improvements to WindRose resampling
  docs/wind_data_user.ipynb
  examples/003_wind_data_objects.py
  examples/examples_wind_data/001_wind_data_comparisons.py
  floris/layout_visualization.py
  floris/wind_data.py
  tests/wind_data_integration_test.py
Labels: enhancement, v4

#877 Add approximate FLORIS model
  examples/examples_uncertain/001_uncertain_model_params.py
  examples/examples_uncertain/002_approx_floris_model.py
  floris/__init__.py
  floris/uncertain_floris_model.py
  tests/uncertain_floris_model_integration_test.py
Labels: v4

#890 [BUGFIX] Incorrect indexing to hub heights in `Farm.coordinates()`
  floris/core/farm.py
Labels: bug
