Repository NREL/floris, pull requests merged in 2024-09, with the labels that each got.

#976 Add gridded layout optimizer
  docs/layout_optimization.md
  examples/examples_layout_optimization/004_generate_gridded_layout.py
  examples/examples_layout_optimization/005_layout_optimization_complex_boundary.py
  floris/optimization/layout_optimization/layout_optimization_base.py
  floris/optimization/layout_optimization/layout_optimization_gridded.py
  tests/layout_optimization_integration_test.py
Labels: floris.optimization, new-feature

#975 Add features to UncertainFlorisModel
  floris/uncertain_floris_model.py
  tests/uncertain_floris_model_integration_test.py
  tests/wind_rose_wrg_test.py
Labels: enhancement

#969 Improved Wind Rose Plot (v2)
  docs/wind_data_user.ipynb
  examples/examples_wind_data/001_wind_data_comparisons.py
  floris/wind_data.py
Labels: enhancement

#984 [BUGFIX] Gridded layout opt incorrectly generating spanning grid
  floris/optimization/layout_optimization/layout_optimization_gridded.py
Labels: bug, enhancement
