Repository NREL/floris, pull requests merged in 2024-02, with the labels that each got.

#782 Convert turbulence intensity from single value to n_findex length array
  examples/12_optimize_yaw_in_parallel.py
  examples/19_streamlit_demo.py
  examples/34_wind_data.py
  examples/35_sweep_ti.py
  examples/36_generate_ti.py
  examples/inputs/cc.yaml
  examples/inputs/emgauss.yaml
  examples/inputs/gch.yaml
  examples/inputs/gch_heterogeneous_inflow.yaml
  examples/inputs/gch_multi_dim_cp_ct.yaml
  examples/inputs/gch_multiple_turbine_types.yaml
  examples/inputs/jensen.yaml
  examples/inputs/turbopark.yaml
  examples/inputs_floating/emgauss_fixed.yaml
  examples/inputs_floating/emgauss_floating.yaml
  examples/inputs_floating/emgauss_floating_fixedtilt15.yaml
  examples/inputs_floating/emgauss_floating_fixedtilt5.yaml
  examples/inputs_floating/gch_fixed.yaml
  examples/inputs_floating/gch_floating.yaml
  examples/inputs_floating/gch_floating_defined_floating.yaml
  floris/simulation/flow_field.py
  floris/simulation/solver.py
  floris/simulation/wake_velocity/turbopark.py
  floris/tools/floris_interface.py
  floris/tools/optimization/yaw_optimization/yaw_optimization_base.py
  floris/tools/parallel_computing_interface.py
  floris/tools/uncertainty_interface.py
  floris/tools/wind_data.py
  floris/type_dec.py
  tests/conftest.py
  tests/data/input_full.yaml
  tests/floris_interface_test.py
  tests/floris_unit_test.py
  tests/flow_field_unit_test.py
  tests/type_dec_unit_test.py
  tests/wind_data_test.py
Labels: v4

#795 [BUGFIX] Bad import in convert_turbine_v3_to_v4.py
  floris/tools/convert_turbine_v3_to_v4.py
Labels: bug, v4

#781 Add support for multiple turbine types in calculate_horizontal_plane_with_turbines()
  floris/tools/visualization.py
Labels: bug

#783 Add de-rating op model
  examples/40_test_derating.py
  floris/simulation/farm.py
  floris/simulation/floris.py
  floris/simulation/solver.py
  floris/simulation/turbine/__init__.py
  floris/simulation/turbine/operation_models.py
  floris/simulation/turbine/turbine.py
  floris/tools/floris_interface.py
  tests/farm_unit_test.py
  tests/floris_interface_test.py
  tests/reg_tests/cumulative_curl_regression_test.py
  tests/reg_tests/empirical_gauss_regression_test.py
  tests/reg_tests/floris_interface_regression_test.py
  tests/reg_tests/gauss_regression_test.py
  tests/reg_tests/jensen_jimenez_regression_test.py
  tests/reg_tests/none_regression_test.py
  tests/reg_tests/turbopark_regression_test.py
  tests/turbine_multi_dim_unit_test.py
  tests/turbine_operation_models_test.py
  tests/turbine_unit_test.py
Labels: enhancement, v4

#793 Validate and test wind direction and wind speed
  floris/simulation/flow_field.py
  tests/floris_interface_test.py
  tests/flow_field_unit_test.py
  tests/reg_tests/cumulative_curl_regression_test.py
  tests/reg_tests/empirical_gauss_regression_test.py
  tests/reg_tests/gauss_regression_test.py
  tests/reg_tests/jensen_jimenez_regression_test.py
  tests/reg_tests/none_regression_test.py
  tests/reg_tests/turbopark_regression_test.py
Labels: bug

#799 Add support to shut off turbines
  examples/41_test_disable_turbines.py
  floris/tools/floris_interface.py
  tests/floris_interface_test.py
Labels: enhancement, v4

#790 Update yaw and layout optimization tools for 4D
  .github/workflows/check-working-examples.yaml
  examples/10_opt_yaw_single_ws.py
  examples/11_opt_yaw_multiple_ws.py
  examples/12_optimize_yaw.py
  examples/12_optimize_yaw_in_parallel.py
  examples/13_optimize_yaw_with_neighboring_farm.py
  examples/14_compare_yaw_optimizers.py
  examples/15_optimize_layout.py
  examples/16c_optimize_layout_with_heterogeneity.py
  floris/tools/optimization/layout_optimization/layout_optimization_base.py
  floris/tools/optimization/layout_optimization/layout_optimization_pyoptsparse.py
  floris/tools/optimization/yaw_optimization/yaw_optimization_base.py
  floris/tools/optimization/yaw_optimization/yaw_optimization_tools.py
  floris/tools/optimization/yaw_optimization/yaw_optimizer_geometric.py
  floris/tools/optimization/yaw_optimization/yaw_optimizer_scipy.py
  floris/tools/optimization/yaw_optimization/yaw_optimizer_sr.py
  floris/tools/parallel_computing_interface.py
Labels: enhancement, floris.tools, floris.optimization, v4

#811 [BUGFIX] Correct condition when yaw_angles passed to TurboPark model (version 3)
  floris/simulation/solver.py
Labels: bug, floris.simulation

#808 [BUGFIX] Correct condition when yaw_angles passed to TurboPark model
  floris/simulation/solver.py
Labels: bug, floris.simulation

#813 [BUGFIX] Remove secondary effects from TurboPark model
  floris/simulation/solver.py
Labels: bug, v4

#812 Support multidimensional turbine definitions in all wake models
  examples/30_multi_dimensional_cp_ct.py
  examples/inputs/gch.yaml
  examples/inputs/gch_multi_dim_cp_ct.yaml
  floris/simulation/solver.py
  floris/simulation/wake.py
  tests/reg_tests/cumulative_curl_regression_test.py
  tests/reg_tests/empirical_gauss_regression_test.py
  tests/reg_tests/floris_interface_regression_test.py
  tests/reg_tests/gauss_regression_test.py
  tests/reg_tests/jensen_jimenez_regression_test.py
  tests/reg_tests/none_regression_test.py
  tests/reg_tests/turbopark_regression_test.py
Labels: floris.simulation, v4

#818 Update multidim turbine files to use absolute turbine power
  floris/simulation/turbine/turbine.py
  floris/turbine_library/iea_15MW_multi_dim_Tp_Hs.csv
  tests/conftest.py
  tests/turbine_multi_dim_unit_test.py
Labels: enhancement, v4

#819 Remove unused code from floris.tools and add tool reg tests
  .github/workflows/check-working-examples.yaml
  docs/examples.md
  examples/08_calc_aep_from_rose_use_class.py
  examples/19_streamlit_demo.py
  floris/tools/__init__.py
  floris/tools/floris_interface_legacy_reader.py
  floris/tools/interface_utilities.py
  floris/tools/optimization/__init__.py
  floris/tools/optimization/legacy/__init__.py
  floris/tools/optimization/legacy/pyoptsparse/__init__.py
  floris/tools/optimization/legacy/pyoptsparse/layout.py
  floris/tools/optimization/legacy/pyoptsparse/optimization.py
  floris/tools/optimization/legacy/pyoptsparse/power_density.py
  floris/tools/optimization/legacy/pyoptsparse/yaw.py
  floris/tools/optimization/legacy/scipy/__init__.py
  floris/tools/optimization/legacy/scipy/base_COE.py
  floris/tools/optimization/legacy/scipy/cluster_turbines.py
  floris/tools/optimization/legacy/scipy/derive_downstream_turbines.py
  floris/tools/optimization/legacy/scipy/layout.py
  floris/tools/optimization/legacy/scipy/layout_height.py
  floris/tools/optimization/legacy/scipy/optimization.py
  floris/tools/optimization/legacy/scipy/power_density.py
  floris/tools/optimization/legacy/scipy/power_density_1D.py
  floris/tools/optimization/legacy/scipy/yaw.py
  floris/tools/optimization/legacy/scipy/yaw_clustered.py
  floris/tools/optimization/legacy/scipy/yaw_wind_rose.py
  floris/tools/optimization/legacy/scipy/yaw_wind_rose_clustered.py
  floris/tools/optimization/legacy/scipy/yaw_wind_rose_parallel.py
  floris/tools/optimization/legacy/scipy/yaw_wind_rose_parallel_clustered.py
  floris/tools/rews.py
  pyproject.toml
  tests/base_unit_test.py
  tests/floris_interface_integration_test.py
  tests/parallel_computing_interface_integration_test.py
  tests/reg_tests/scipy_layout_opt_regression.py
  tests/reg_tests/yaw_optimization_regression_test.py
  tests/turbine_operation_models_integration_test.py
  tests/wind_data_integration_test.py
Labels: enhancement, v4

#824 WindTIRose class with TI as a third wind rose dimension
  examples/34_wind_data.py
  floris/tools/__init__.py
  floris/tools/wind_data.py
  tests/wind_data_integration_test.py
Labels: new-feature, v4

#823 Move FlorisInterface .reinitialize() / .calculate_wake() to .set() / .run()
  examples/01_opening_floris_computing_power.py
  examples/02_visualizations.py
  examples/03_making_adjustments.py
  examples/04_sweep_wind_directions.py
  examples/05_sweep_wind_speeds.py
  examples/06_sweep_wind_conditions.py
  examples/07_calc_aep_from_rose.py
  examples/09_compare_farm_power_with_neighbor.py
  examples/10_opt_yaw_single_ws.py
  examples/11_opt_yaw_multiple_ws.py
  examples/12_optimize_yaw.py
  examples/12_optimize_yaw_in_parallel.py
  examples/13_optimize_yaw_with_neighboring_farm.py
  examples/14_compare_yaw_optimizers.py
  examples/15_optimize_layout.py
  examples/16_heterogeneous_inflow.py
  examples/16b_heterogeneity_multiple_ws_wd.py
  examples/16c_optimize_layout_with_heterogeneity.py
  examples/18_check_turbine.py
  examples/21_demo_time_series.py
  examples/22_get_wind_speed_at_turbines.py
  examples/23_visualize_layout.py
  examples/24_floating_turbine_models.py
  examples/25_tilt_driven_vertical_wake_deflection.py
  examples/26_empirical_gauss_velocity_deficit_parameters.py
  examples/27_empirical_gauss_deflection_parameters.py
  examples/28_extract_wind_speed_at_points.py
  examples/29_floating_vs_fixedbottom_farm.py
  examples/30_multi_dimensional_cp_ct.py
  examples/31_multi_dimensional_cp_ct_2Hs.py
  examples/32_plot_velocity_deficit_profiles.py
  examples/33_specify_turbine_power_curve.py
  examples/34_wind_data.py
  examples/35_sweep_ti.py
  examples/40_test_derating.py
  examples/41_test_disable_turbines.py
  floris/simulation/flow_field.py
  floris/simulation/turbine/operation_models.py
  floris/tools/floris_interface.py
  floris/tools/optimization/layout_optimization/layout_optimization_base.py
  floris/tools/optimization/layout_optimization/layout_optimization_boundary_grid.py
  floris/tools/optimization/layout_optimization/layout_optimization_pyoptsparse.py
  floris/tools/optimization/layout_optimization/layout_optimization_scipy.py
  floris/tools/optimization/yaw_optimization/yaw_optimization_base.py
  floris/tools/optimization/yaw_optimization/yaw_optimizer_scipy.py
  floris/tools/parallel_computing_interface.py
  floris/tools/visualization.py
  tests/floris_interface_integration_test.py
  tests/parallel_computing_interface_integration_test.py
  tests/reg_tests/yaw_optimization_regression_test.py
Labels: enhancement, floris.tools, v4
