Repository NREL/floris, pull requests merged in 2024-05, with the labels that each got.

#880 Add test for v3_to_v4 input file converters
  .gitignore
  tests/convert_v3_to_v4_test.py
  tests/v3_to_v4_convert_test/gch.yaml
  tests/v3_to_v4_convert_test/nrel_5MW_v3.yaml
Labels: enhancement

#888 Peak shaving turbine operation model
  docs/operation_models_user.ipynb
  examples/examples_control_types/005_peak_shaving.py
  floris/core/solver.py
  floris/core/turbine/__init__.py
  floris/core/turbine/operation_models.py
  floris/core/turbine/turbine.py
  floris/floris_model.py
  floris/turbine_library/nrel_5MW.yaml
  tests/conftest.py
  tests/reg_tests/cumulative_curl_regression_test.py
  tests/reg_tests/empirical_gauss_regression_test.py
  tests/reg_tests/gauss_regression_test.py
  tests/reg_tests/jensen_jimenez_regression_test.py
  tests/reg_tests/none_regression_test.py
  tests/reg_tests/turbopark_regression_test.py
  tests/turbine_multi_dim_unit_test.py
  tests/turbine_operation_models_unit_test.py
  tests/turbine_unit_test.py
Labels: new-feature

#894 [BUGFIX] `NoneWakeTurbulence` returns zero (added) turbulence
  examples/002_visualizations.py
  floris/core/wake_turbulence/none.py
  tests/reg_tests/turbulence_models_regression_test.py
Labels: bug

#900 [BUGFIX] Include turbulence_intensities in turbine_previewer.py
  floris/turbine_library/turbine_previewer.py
Labels: bug, documentation
