Repository NREL/floris, pull requests merged in 2024-03, with the labels that each got.

#805 Collect all layout visualization tools in FLORIS
  examples/02_visualizations.py
  examples/03_making_adjustments.py
  examples/16_heterogeneous_inflow.py
  examples/16b_heterogeneity_multiple_ws_wd.py
  examples/17_multiple_turbine_types.py
  examples/23_layout_visualizations.py
  examples/23_visualize_layout.py
  examples/24_floating_turbine_models.py
  examples/25_tilt_driven_vertical_wake_deflection.py
  examples/26_empirical_gauss_velocity_deficit_parameters.py
  examples/27_empirical_gauss_deflection_parameters.py
  examples/29_floating_vs_fixedbottom_farm.py
  examples/32_plot_velocity_deficit_profiles.py
  floris/tools/__init__.py
  floris/tools/floris_interface.py
  floris/tools/flow_visualization.py
  floris/tools/layout_functions.py
  floris/tools/layout_visualization.py
  tests/layout_visualization_test.py
Labels: enhancement, v4

#828 [Bugfix] Cast yaw angles to np.ndarray on set
  floris/simulation/farm.py
  floris/simulation/floris.py
  floris/tools/floris_interface.py
  floris/tools/uncertainty_interface.py
  tests/farm_unit_test.py
  tests/floris_interface_integration_test.py
Labels: bug

#821 Update uncertainty interface to 4d, new API
  examples/20_calculate_farm_power_with_uncertainty.py
  floris/tools/uncertainty_interface.py
  tests/uncertainty_interface_integration_test.py
Labels: enhancement, v4

#822 Drive layout optimizations using WindData objects
  examples/15_optimize_layout.py
  examples/16c_optimize_layout_with_heterogeneity.py
  floris/tools/__init__.py
  floris/tools/optimization/layout_optimization/layout_optimization_base.py
  floris/tools/optimization/layout_optimization/layout_optimization_pyoptsparse.py
  floris/tools/optimization/layout_optimization/layout_optimization_pyoptsparse_spread.py
  floris/tools/optimization/layout_optimization/layout_optimization_scipy.py
  tests/layout_optimization_integration_test.py
Labels: v4

#831 Require TI must be length n_findex in core code
  examples/01_opening_floris_computing_power.py
  examples/04_sweep_wind_directions.py
  examples/05_sweep_wind_speeds.py
  examples/06_sweep_wind_conditions.py
  examples/07_calc_aep_from_rose.py
  examples/09_compare_farm_power_with_neighbor.py
  examples/10_opt_yaw_single_ws.py
  examples/11_opt_yaw_multiple_ws.py
  examples/12_optimize_yaw.py
  examples/12_optimize_yaw_in_parallel.py
  examples/13_optimize_yaw_with_neighboring_farm.py
  examples/14_compare_yaw_optimizers.py
  examples/15_optimize_layout.py
  examples/16b_heterogeneity_multiple_ws_wd.py
  examples/16c_optimize_layout_with_heterogeneity.py
  examples/18_check_turbine.py
  examples/21_demo_time_series.py
  examples/24_floating_turbine_models.py
  examples/28_extract_wind_speed_at_points.py
  examples/29_floating_vs_fixedbottom_farm.py
  examples/30_multi_dimensional_cp_ct.py
  examples/31_multi_dimensional_cp_ct_2Hs.py
  examples/33_specify_turbine_power_curve.py
  examples/36_generate_ti.py
  examples/40_test_derating.py
  examples/41_test_disable_turbines.py
  floris/simulation/flow_field.py
  floris/tools/floris_interface.py
  floris/tools/wind_data.py
  profiling/quality_metrics.py
  tests/conftest.py
  tests/floris_interface_integration_test.py
  tests/reg_tests/cumulative_curl_regression_test.py
  tests/reg_tests/empirical_gauss_regression_test.py
  tests/reg_tests/gauss_regression_test.py
  tests/reg_tests/jensen_jimenez_regression_test.py
  tests/reg_tests/none_regression_test.py
  tests/reg_tests/turbopark_regression_test.py
  tests/reg_tests/yaw_optimization_regression_test.py
  tests/wind_data_integration_test.py
Labels: v4

#837 Add TI as input for calculate plane functions
  floris/tools/floris_interface.py
  floris/tools/flow_visualization.py
  tests/floris_interface_integration_test.py
Labels: bug, v4

#846 [BUGFIX] Coordinates getter on Farm class
  floris/simulation/farm.py
Labels: bug

#840 Add utilities for floris models
  floris/floris_model.py
  floris/utilities.py
  tests/floris_model_integration_test.py
  tests/utilities_unit_test.py
Labels: v4

#850 Allow to fix yaw to nominal wind direction
  floris/uncertain_floris_model.py
  tests/uncertain_floris_model_integration_test.py
Labels: v4

#848 Add CSV reader for WindRose
  floris/wind_data.py
  tests/data/wind_rose.csv
  tests/data/wind_ti_rose.csv
  tests/wind_data_integration_test.py
Labels: enhancement, v4

#849 Save WindData onto FlorisModel and simplify post-`run()` calls
  examples/07_calc_aep_from_rose.py
  examples/13_optimize_yaw_with_neighboring_farm.py
  examples/15_optimize_layout.py
  examples/16c_optimize_layout_with_heterogeneity.py
  examples/29_floating_vs_fixedbottom_farm.py
  examples/34_wind_data.py
  floris/floris_model.py
  floris/optimization/layout_optimization/layout_optimization_base.py
  floris/optimization/layout_optimization/layout_optimization_pyoptsparse.py
  floris/optimization/layout_optimization/layout_optimization_pyoptsparse_spread.py
  floris/optimization/layout_optimization/layout_optimization_scipy.py
  floris/uncertain_floris_model.py
  floris/wind_data.py
  tests/floris_model_integration_test.py
  tests/layout_optimization_integration_test.py
  tests/parallel_floris_model_integration_test.py
  tests/uncertain_floris_model_integration_test.py
  tests/wind_data_integration_test.py
Labels: enhancement, v4

#853 Documentation improvements and fixes
  docs/_config.yml
  docs/_templates/custom-class-template.rst
  docs/_templates/custom-module-template.rst
  docs/_toc.yml
  docs/advanced_concepts.ipynb
  docs/api_docs.md
  docs/architecture.md
  docs/dev_guide.md
  docs/examples.md
  docs/floris_101.ipynb
  docs/index.md
  docs/intro_concepts.ipynb
  docs/wake_models.ipynb
  setup.py
Labels: bug, enhancement, documentation
