Repository NREL/floris, pull requests merged in 2024-11, with the labels that each got.

#1020 Remove testing for Mac OS for FLORIS v2
  .github/workflows/continuous-integration-workflow.yaml
Labels: v2.x

#1008 [BUGFIX] Correct grid coordinates for ngrid=1
  floris/simulation/flow_field.py
Labels: bug, v2.x

#1027 Allow yaw optimization with disabled turbines
  examples/examples_control_optimization/008_optimize_yaw_with_disabled_turbines.py
  floris/core/turbine/operation_models.py
  floris/floris_model.py
  floris/optimization/yaw_optimization/yaw_optimization_base.py
  floris/optimization/yaw_optimization/yaw_optimizer_geometric.py
  floris/optimization/yaw_optimization/yaw_optimizer_scipy.py
  floris/optimization/yaw_optimization/yaw_optimizer_sr.py
  tests/floris_model_integration_test.py
  tests/geometric_yaw_unit_test.py
  tests/serial_refine_unit_test.py
Labels: bug, enhancement

#1031 Allow yaw optimization with disabled turbines (into develop)
  examples/examples_control_optimization/008_optimize_yaw_with_disabled_turbines.py
  floris/core/turbine/operation_models.py
  floris/floris_model.py
  floris/optimization/yaw_optimization/yaw_optimization_base.py
  floris/optimization/yaw_optimization/yaw_optimizer_geometric.py
  floris/optimization/yaw_optimization/yaw_optimizer_scipy.py
  floris/optimization/yaw_optimization/yaw_optimizer_sr.py
  tests/floris_model_integration_test.py
  tests/geometric_yaw_unit_test.py
  tests/serial_refine_unit_test.py
Labels: bug, enhancement

#1026 Move all metadata to pyproject.toml
  .github/workflows/python-publish.yml
  docs/dev_guide.md
  floris/__init__.py
  floris/version.py
  pyproject.toml
  setup.py
Labels: enhancement

#1028 [BUGFIX] Reenable legend plotting on WindRose
  floris/wind_data.py
Labels: bug

#1034 Fix docs
  pyproject.toml
  tests/wind_data_integration_test.py
Labels: bug, documentation

#1041 Add warnings about dropping support for python 3.8
  README.md
  docs/index.md
  docs/installation.md
Labels: documentation
