Repository NREL/floris, pull requests merged in 2024-10, with the labels that each got.

#990 Add examples and documentation for ParFlorisModel
  docs/_toc.yml
  docs/advanced_concepts.ipynb
  docs/floris_models.ipynb
  docs/intro_concepts.ipynb
  examples/009_parallel_models.py
  examples/010_compare_farm_power_with_neighbor.py
  examples/examples_control_optimization/005_optimize_yaw_aep_parallel.py
Labels: enhancement, documentation, examples

#997 [BUGFIX] Control setpoints and wind data set on `FlorisModel` copied into `ParFlorisModel`
  floris/par_floris_model.py
Labels: bug

#999 Set ref wind height to -1 for turboparkgauss.yaml
  examples/inputs/turboparkgauss.yaml
Labels: bug

#1000 [BUGFIX] Warn users if the `turbine_type` is set without setting `reference_wind_height`
  floris/floris_model.py
  tests/floris_model_integration_test.py
Labels: bug

#1006 Add flow visualization to wake steering example
  examples/examples_control_optimization/001_opt_yaw_single_ws.py
Labels: enhancement
