Repository NREL/floris, pull requests merged in 2025-03, with the labels that each got.

#1078 Update docs to note the upcoming end of support for python 3.9
  docs/index.md
  docs/installation.md
Labels: documentation

#1084 Add timing data, add missing dtype
  docs/code_quality.ipynb
  examples/inputs/gch.yaml
  floris/core/grid.py
  floris/utilities.py
Labels: enhancement, documentation

#1081 [BUGFIX] AWCTurbine operation model with mixed `awc_modes` inputs
  examples/examples_control_types/004_helix_active_wake_mixing.py
  floris/core/turbine/operation_models.py
  tests/turbine_operation_models_unit_test.py
Labels: bug

#1086 [BUGFIX] Add bokeh requirement for building docs
  pyproject.toml
Labels: bug, documentation
